src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    /**
     * @var Collection<int, Note>
     */
    #[ORM\OneToMany(targetEntity: Note::class, mappedBy: 'user')]
    private Collection $notes;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $photo = null;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return Collection<int, Note>
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): static
    {
        if (!$this->notes->contains($note)) {
            $this->notes->add($note);
            $note->setUser($this);
        }

        return $this;
    }

    public function removeNote(Note $note): static
    {
        if ($this->notes->removeElement($note)) {
            // set the owning side to null (unless already changed)
            if ($note->getUser() === $this) {
                $note->setUser(null);
            }
        }

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }
}

src/Controller/HomePageController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Note;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Psr\Cache\CacheItemPoolInterface; 
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

final class HomePageController extends AbstractController
{
    #[Route('/', name: 'homepage')]
    public function index(): Response
    {

        $user = $this->getUser();
        
        return $this->render('home_page/index.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/documents', name: 'documents')]
    public function documents(): Response
    {

        $user = $this->getUser();
        
        return $this->render('home_page/documents.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/notes', name: 'notes')]
    public function notes(EntityManagerInterface $entityManager): Response
    {

        $user = $this->getUser();
        //get Notes of the user
        $notes = $entityManager->getRepository(Note::class)->findBy(['user' => $user]);

        return $this->render('home_page/notes.html.twig', [
            'user' => $user,
            'notes' => $notes,
        ]);
    }

    #[Route('/messages', name: 'messages')]
    public function messages(): Response
    {
        $user = $this->getUser();
        
        return $this->render('home_page/messages.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/securite', name: 'securite')]
    public function securite(Request $request): Response
    {
        $user = $this->getUser();
        $message = $request->query->get('message');

        return $this->render('home_page/securite.html.twig', [
            'user' => $user,
            'message' => $message,
        ]);
    }

    #[Route('/plan', name: 'plan')]
    public function plan(): Response
    {
        $user = $this->getUser();
        
        return $this->render('home_page/plan.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/update-button', name: 'update_button', methods: ['POST'])]
    public function updateButton(Request $request, CacheItemPoolInterface $cache): Response
    {
        $value = $request->request->get('value');

        $item = $cache->getItem('panic_button');
        $item->set($value);
        $cache->save($item);

        return new Response('OK');
    }

    #[Route('/get-button-status', name: 'get_button_status', methods: ['GET'])]
    public function getButtonStatus(CacheItemPoolInterface  $cache): Response
    {
        $item = $cache->getItem('panic_button');
        $value = $item->isHit() ? $item->get() : '0';

        return new Response($value);
    }

    #[Route('/secret/home', name: 'secret_home')]
    public function secretHome(Request $request): Response
    {
        $user = $this->getUser();
        $message = $request->query->get('message');

        
        return $this->render('dark/index.html.twig', [
            'user' => $user,
            'message' => $message,
        ]);
    }

    #[Route('/secret/documents', name: 'secret_documents')]
    public function secretDocuments(): Response
    {
        $user = $this->getUser();
        
        return $this->render('dark/documents.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/secret/notes', name: 'secret_notes')]
    public function secretNotes(EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        //get Notes of the user
        $notes = $entityManager->getRepository(Note::class)->findBy(['user' => $user]);
        
        return $this->render('dark/notes.html.twig', [
            'user' => $user,
            'notes' => $notes,
        ]);
    }

    #[Route('/button', name: 'button')]
    public function button(CacheItemPoolInterface $cache, EntityManagerInterface $entityManager, TokenStorageInterface $tokenStorage): Response
    {
        $item = $cache->getItem('panic_button');
        $value = $item->isHit() ? $item->get() : '0';
        $message = '';

        $user = $this->getUser();

        if ($value == 1) {
            if ($user) {
                $user->setRoles(['ROLE_DARK']);
                $entityManager->persist($user);
                $entityManager->flush();

                // Met à jour la session pour prendre en compte le nouveau rôle
                $token = new UsernamePasswordToken($user, 'main', $user->getRoles());
                $tokenStorage->setToken($token);

            $message = 'Sécurité enclenchée, face cachée activée.';
            return $this->redirectToRoute('secret_home', [
            'message' => $message,
        ]);
            }
        } else {
            $message = 'Erreur de sécurité, il semble manquer quelque chose.';
        }

        return $this->redirectToRoute('securite', [
            'message' => $message,
        ]);
    }

    #[Route('/download/{filename}', name: 'download_file')]
    public function downloadFile(string $filename): Response
    {
        $filePath = __DIR__ . '/../../public/uploads/' . $filename;

        if (!file_exists($filePath)) {
            throw $this->createNotFoundException('File not found');
        }

        return $this->file($filePath, null, ResponseHeaderBag::DISPOSITION_ATTACHMENT);
    }

}

templates/home_page/plan.html.twig
{% extends 'base.html.twig' %}

{% block title %}Life Insurance{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('style/style.css') }}">
    <link rel="stylesheet" href="{{ asset('style/template.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer" />

{% endblock %}

{% block body %}

<div id="page-top">
  <!-- Page Wrapper -->
  <div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
      <div class="sidebar-brand d-flex align-items-center justify-content-center" >
        <img src="{{asset('images/life_logo.png')}}" style="width: 150px; height: 75px;" alt="">
      </div>

      <!-- Divider -->
      <hr class="sidebar-divider my-0" />

      <li class="nav-item">
        <a class="nav-link" href="{{ path('homepage') }}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <li class="nav-item">

        <a  class="nav-link collapsed" href="{{ path('documents') }}" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
          aria-controls="collapseTwo">
          <i class="fas fa-file"></i>
          <span>Documents</span>
        </a>
      </li>

      <li class="nav-item">
      <a class="nav-link collapsed" href="{{ path('notes') }}" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
          aria-controls="collapseTwo">
          <i class="fas fa-note-sticky"></i>
          <span>Notes</span>
        </a>
        
      </li>

      <li class="nav-item">
      <a style="font-weight:bold" class="nav-link collapsed" href="{{ path('plan') }}" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
          aria-controls="collapseTwo">
          <i class="fas fa-map"></i>
          <span>Plan de l'entreprise</span>
        </a>
      </li>

      {% if is_granted("ROLE_SECU") %}
      <li class="nav-item">
      <a class="nav-link collapsed" href="{{ path('securite') }}" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
          aria-controls="collapseTwo">
          <i class="fas fa-shield-halved"></i>
          <span>Sécurité</span>
        </a>
      </li>
      {% endif %}

      {% if is_granted("ROLE_DARK") %}
      <li class="nav-item">
      <a class="nav-link collapsed" href="{{ path('secret_home') }}" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
          aria-controls="collapseTwo">
          <i class="fas fa-user-secret"></i>
          <span>Face cachée</span>
        </a>
        
      </li>
      {% endif %}

      
      <!-- Sidebar Toggler (Sidebar) -->
      <li class="nav-item mt-auto">
        <a class="nav-link" data-turbo="false" href="{{ path('logout') }}">
          <i class="fas fa-sign-out-alt"></i>
          <span>Se déconnecter</span>
        </a>
      </li>
      
    </ul>

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
      <!-- Topbar -->
      <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
        
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
              aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">
          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
              aria-labelledby="searchDropdown">
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                    aria-label="Search" aria-describedby="basic-addon2" />
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>

          <!-- Nav Item - Alerts -->
          <li class="nav-item dropdown no-arrow mx-1">
            {# <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-bell fa-fw"></i>

              <span class="badge badge-danger badge-counter">3+</span>
            </a> #}

            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
              aria-labelledby="alertsDropdown">
              <h6 class="dropdown-header">Alerts Center</h6>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="mr-3">
                  <div class="icon-circle bg-primary">
                    <i class="fas fa-file-alt text-white"></i>
                  </div>
                </div>
                <div>
                  <div class="small text-gray-500">December 12, 2019</div>
                  <span class="font-weight-bold">A new monthly report is ready to download!</span>
                </div>
              </a>

              <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
          </li>

          <!-- Nav Item - Messages -->
          <li class="nav-item dropdown no-arrow mx-1">
            
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
              aria-labelledby="messagesDropdown">
              <h6 class="dropdown-header">Message Center</h6>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <div class="dropdown-list-image mr-3">
                  <img class="rounded-circle" src="images/undraw_profile.svg" alt="..." />
                  <div class="status-indicator bg-success"></div>
                </div>
                <div class="font-weight-bold">
                  <div class="text-truncate">
                    Hi there! I am wondering if you can help me with a problem
                    I've been having.
                  </div>
                  <div class="small text-gray-500">Emily Fowler · 58m</div>
                </div>
              </a>

              <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
          </li>

          <div class="topbar-divider d-none d-sm-block"></div>

          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle"x id="userDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.prenom}} {{user.nom}}</span>
              {% if user.photo is not null %}
              <img class="img-profile rounded-circle" src="images/{{user.photo}}" />
              {% else %}
              <img class="img-profile rounded-circle" src="images/undraw_profile.svg" />
              {% endif %}
              
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Profile
              </a>
              <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Settings
              </a>
              <a class="dropdown-item" href="#">
                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                Activity Log
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Logout
              </a>
            </div>
          </li>
        </ul>
      </nav>

      <div id="content">
        <div class="container-fluid">
          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Plan de l'entreprise</h1>
            {# <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                class="fas fa-download fa-sm text-white-50"></i> Generate
              Report</a> #}
          </div>

          <!-- Content Row -->

          <div class="row">

          <embed src="{{asset('uploads/Plan_Salle2.pdf')}}" type="application/pdf" width="100%" height="600px" />

          {# <a href="{{asset('uploads/Plan_Salle2.pdf')}}" target="_blank">
            <img src="{{asset('images/sophie.png')}}" alt="Aperçu PDF" style="width:100%; max-width:600px;" />
        </a> #}

          </div>
          
        </div>
      </div>


    </div>
  </div>

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">
          Select "Logout" below if you are ready to end your current session.
        </div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">
            Cancel
          </button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>
  </div>
  
  <script>
    
  </script>

{% endblock %}